<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[Launch browser Sussess]]>
    </line>
    <line>
      <![CDATA[UserId And Password Data Filled Properlly ]]>
    </line>
    <line>
      <![CDATA[Pin Data Filled Properlly ]]>
    </line>
    <line>
      <![CDATA[Taking ScreenShot]]>
    </line>
    <line>
      <![CDATA[Logout Sussess ]]>
    </line>
    <line>
      <![CDATA[Close browser Sussess]]>
    </line>
  </reporter-output>
  <suite started-at="2022-04-04T13:33:43 IST" name="Default suite" finished-at="2022-04-04T13:34:12 IST" duration-ms="28814">
    <groups>
    </groups>
    <test started-at="2022-04-04T13:33:43 IST" name="Default test" finished-at="2022-04-04T13:34:12 IST" duration-ms="28814">
      <class name="KiteApp_With_TestNG.KiteApp_with_TestNG">
        <test-method is-config="true" signature="LaunchingBrowser()[pri:0, instance:KiteApp_With_TestNG.KiteApp_with_TestNG@67f639d3]" started-at="2022-04-04T13:33:43 IST" name="LaunchingBrowser" finished-at="2022-04-04T13:33:55 IST" duration-ms="11862" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Launch browser Sussess]]>
            </line>
          </reporter-output>
        </test-method> <!-- LaunchingBrowser -->
        <test-method is-config="true" signature="KiteAppLogin()[pri:0, instance:KiteApp_With_TestNG.KiteApp_with_TestNG@67f639d3]" started-at="2022-04-04T13:33:55 IST" name="KiteAppLogin" finished-at="2022-04-04T13:34:01 IST" duration-ms="5908" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[UserId And Password Data Filled Properlly ]]>
            </line>
            <line>
              <![CDATA[Pin Data Filled Properlly ]]>
            </line>
          </reporter-output>
        </test-method> <!-- KiteAppLogin -->
        <test-method signature="ValidatingKiteHomePageId()[pri:0, instance:KiteApp_With_TestNG.KiteApp_with_TestNG@67f639d3]" started-at="2022-04-04T13:34:01 IST" name="ValidatingKiteHomePageId" finished-at="2022-04-04T13:34:08 IST" duration-ms="7160" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Actual UserId is Not Matchind with Expected UserId expected [BW5772] but found [HD5857]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Actual UserId is Not Matchind with Expected UserId expected [BW5772] but found [HD5857]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at KiteApp_With_TestNG.KiteApp_with_TestNG.ValidatingKiteHomePageId(KiteApp_with_TestNG.java:59)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Taking ScreenShot]]>
            </line>
          </reporter-output>
        </test-method> <!-- ValidatingKiteHomePageId -->
        <test-method is-config="true" signature="logoutFromKiteApp()[pri:0, instance:KiteApp_With_TestNG.KiteApp_with_TestNG@67f639d3]" started-at="2022-04-04T13:34:09 IST" name="logoutFromKiteApp" finished-at="2022-04-04T13:34:12 IST" duration-ms="2858" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Logout Sussess ]]>
            </line>
          </reporter-output>
        </test-method> <!-- logoutFromKiteApp -->
        <test-method is-config="true" signature="KiteAppClose()[pri:0, instance:KiteApp_With_TestNG.KiteApp_with_TestNG@67f639d3]" started-at="2022-04-04T13:34:12 IST" name="KiteAppClose" finished-at="2022-04-04T13:34:12 IST" duration-ms="236" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Close browser Sussess]]>
            </line>
          </reporter-output>
        </test-method> <!-- KiteAppClose -->
      </class> <!-- KiteApp_With_TestNG.KiteApp_with_TestNG -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
